<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <!--<PackageReference Include="xunit" Version="2.9.3" />-->
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestReactAspire.Shared\RestReactAspire.Shared.csproj" />
    <ProjectReference Include="..\RestReactAspire.Server\RestReactAspire.Server.csproj" />
    <ProjectReference Include="..\RestReactAspire.PatientService\RestReactAspire.PatientService.csproj" />
    <ProjectReference Include="..\RestReactAspire.DoctorService\RestReactAspire.DoctorService.csproj" />
    <ProjectReference Include="..\RestReactAspire.ExamService\RestReactAspire.ExamService.csproj" />
    <ProjectReference Include="..\RestReactAspire.StatisticsService\RestReactAspire.StatisticsService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>