<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>80af98e1-d902-4d1e-ac5c-2f56939ef342</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestReactAspire.Server\RestReactAspire.Server.csproj" />
    <ProjectReference Include="..\RestReactAspire.PatientService\RestReactAspire.PatientService.csproj" />
    <ProjectReference Include="..\RestReactAspire.DoctorService\RestReactAspire.DoctorService.csproj" />
    <ProjectReference Include="..\RestReactAspire.ExamService\RestReactAspire.ExamService.csproj" />
    <ProjectReference Include="..\RestReactAspire.StatisticsService\RestReactAspire.StatisticsService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
    <PackageReference Include="MessagePack" Version="2.5.302" />
  </ItemGroup>
</Project>
